name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - uses: actions/checkout@v2
    - name: Build
      run: cd opensearch-operator && CGO_ENABLED=0 make --warn-undefined-variables
    - name: Upload
      uses: fnkr/github-action-ghr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: ./opensearch-operator/bin
        GHR_COMPRESS: gz
